networks:
  network4:
    name: network4

services:
  nginx2:
    container_name: nginx2
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .\vhost.conf:/etc/nginx/conf.d/default.conf
      - .\www:/var/www/public_html
    networks: 
      - network4
    depends_on:
      - php2
      - mysql2

  php2:
    container_name: php2
    build: .\images\php
    volumes: 
      - .\www:/var/www/public_html
    networks: 
      - network4
    depends_on:
      - mysql2      
  mysql2:
    container_name: mysql2
    image: mysql
    volumes:
      - .\mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localhost
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks: 
      - network4
  phpmyadmin2:
    container_name: phpmyadmin2
    image: phpmyadmin
    ports:
      - "1500:80"
    environment:
      PMA_HOST: mysql2
    depends_on:
      - mysql2
    networks: 
      - network4
